### ISSUE TITLE
Plugin not working with PyCharm 2020.1

### ISSUE THREAD

**Issue by fidelleon** [tonybaloney/pycharm-security#107]
After upgrading PyCharm 2020.0 to 2020.1, launching the application gives the following event log entry:

> Plugin Error: Plugin "Python Security" is incompatible (until build 193.SNAPSHOT < PY-201.6668.115)

**Comment by tonybaloney** [comment]
Thanks, this is a bug in IDEA but I'm releasing a new version now. https://youtrack.jetbrains.com/issue/IDEA-237113 
My understanding is that by releasing another version (with no changes), it will show as compatible

**Comment by tonybaloney** [comment]
Should be fixed in 1.16.0, will take a few hours for this to appear in the marketplace https://github.com/tonybaloney/pycharm-security/releases/tag/1.16.0

**Comment by fidelleon** [comment]
Confirmed as fixed in PyCharm 2020.1 for Windows, Linux and MacOS
