### ISSUE TITLE
Fixers don't work for Mako and Jinja2 in edge case

### ISSUE THREAD

**Issue by koxudaxi** [tonybaloney/pycharm-security#118]
Thank you for creating a great plugin.

**Describe the bug**
`JinjaAutoInspectFixer` and `MakoFilter`  don't work correctly in this case.

**To Reproduce**
I fixed `Environment` and `Template` in  this code with fixers
Before:
```python
from mako.template import Template
from jinja2 import Environment, PackageLoader 

Environment(loader=PackageLoader(package_path='yourapplication',package_name='templates'))
Template(str(value='abc'))
```
After:
```python
from mako.template import Template
from jinja2 import Environment, PackageLoader 

Environment(loader=PackageLoader(package_path='yourapplication', package_name='templates', autoescape=True))
Template(str(value='abc', default_filters=['h']))
```

If an argument has keyword arguments then, Fixers insert an argument to nested argument.
the arguments have to be a top-level arguments

**Screenshots**
![Peek 2020-05-21 02-23](https://user-images.githubusercontent.com/630670/82477349-52d6ab80-9b0a-11ea-9676-051d32d095e8.gif)

**Additional context**
 - Plugin Version 1.18.0
 - PyCharm Pro 2020.1.1
 - Python Version 3.8.0

**Comment by tonybaloney** [comment]
Fix works really well, thanks for the detailed report
