### ISSUE TITLE
Update insecure.json regularly

### ISSUE THREAD

**Issue by charleswhchan** [tonybaloney/pycharm-security#132]
It looks like safety-db updates their database once a month. 
https://github.com/pyupio/safety-db/commits/master/data/insecure.json

Is it possible for this project to follow the same cadence? There were some false warnings that was fixed after Apr 14th release.

PS. LMK I should create a PR to update the DB.

**Comment by tonybaloney** [comment]
thanks for raising this, the PyUp database wasn't updated for about 9 months when I initially developed this plugin.
In the settings, you can point to a URL, instead of using the embedded version.

**Comment by tonybaloney** [comment]
also, the Snyk integration uses a live database.

**Comment by charleswhchan** [comment]
Good to know. Thanks @tonybaloney 

The URL option works for me. I am happy with this solution so feel free to close the ticket if appropriate.
