### ISSUE TITLE
Python security 1.23.1 - Pycharm 2021.1 - Incompatible requires IDE BUILD 203.* or older

### ISSUE THREAD

**Issue by bart-at-qqdatafruits** [tonybaloney/pycharm-security#207]
- Summary: ubyntu 20.4.2 LTS - Pycharm 2021.1 - Python security 1.23.1 - Incompatible requires IDE BUILD 203.* or older

- to reproduce:

updated Pycharm
received plugin error

- observation

Changes in Pycharm often break Plugins
Python security 1.23.1 is broken on Pycharm 2021.1 

- further details on Pycharm affected

PyCharm 2021.1 (Professional Edition)
Build #PY-211.6693.115, built on April 6, 2021
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-70-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Non-Bundled Plugins: com.intellij.javafx (1.0.3), R4Intellij (211.6693.2), com.intellij.bigdatatools (0.5.44)
Current Desktop: ubuntu:GNOME

- intent: sharing this information

**Comment by cowboy-cod3r** [comment]
Same with Intellij 2021.1

**Comment by tonybaloney** [comment]
I just shipped a release with 211.* support. IT should be in the plugin store shortly.

**Comment by bart-at-qqdatafruits** [comment]
Hi @tonybaloney,

You fixed it.

Thank you.

Regards Bart,
