### ISSUE TITLE
Plugin 'Python Security' (version '1.25.0') is not compatible with the current version of the IDE, because it requires build 221.* or older but the current build is PC-222.3345.131

### ISSUE THREAD

**Issue by crystalbowie** [tonybaloney/pycharm-security#360]
# Feature Request

Plugin 'Python Security' (version '1.25.0') is not compatible with the current version of the IDE, because it requires build 221.* or older but the current build is PC-222.3345.131

**Comment by tonybaloney** [comment]
Thanks for the report. I'll patch the specifier

**Comment by tonybaloney** [comment]
Released a patch in 1.26.0, it'll be available in the JetBrains store later today
