### ISSUE TITLE
Provide references for multi-project security vulnerability notifications

### ISSUE THREAD

**Issue by fmigneault** [tonybaloney/pycharm-security#385]
# Feature Request

- Is it for PyCharm? Yes
- Is it for the GitHub Action or Docker container? No

## Details

When multi-projects are used in PyCharm, multiple virtual environments can be used simultaneously. Because each one will have different sets of package dependencies, any notification regarding Python Security CVE are hard to resolve since the user cannot easily figure out for which environment the flagged notification applies to. The generated notification should better guide the user to which explicit package is affected.

Originally created in https://youtrack.jetbrains.com/issue/PY-56849

### Steps to Reproduce

1. Create multiple projects with different virtual environments and dependencies.
2. In one of the environment, purposely install a package (any) that will trigger a CVE to be detected when analyzed.
3. Open the projects and attach them together to create a multi-project view.
4. Once CVE are analyzed and detected, see how produced notifications do not provide any indication about which environment is affected.

### Expected Result

A link or path displaying the specific package, the specific project, or the relevant virtual environment should be provided to help the developer inspect or correct the affected package.

### Actual Result

Without better references, analyzing massive multi-project CVEs is impossible, since all sub-projects could use different dependencies. It is extremely counter-productive to look up all possibilities each time any environment and/or installed packages change.

**Comment by tonybaloney** [comment]
Thanks for the suggestion @fmigneault that sounds like a complicated setup. When this plugin was originally made, PyCharm supported neither multiple projects or package managers. 

I've had a look at the API. The plugin gets:

- A Project interface, which has a name
- Each Project has a set of Sdk's, which each have an interface for fetching a list of installed package
- Each package has a version, name and location
- There is no API (that I can find) for getting the name of the Package Manager, but I am looping over all package managers in a project

Have experimented with adding some additional messages to the notifications:
- The name of the project
- The location of the package if it has a vulnerability

<img width="612" alt="screenshot 2023-03-22 at 13 11 37" src="https://user-images.githubusercontent.com/1532417/226784115-e0ba1395-f0ad-4c45-8e2b-5a70a3a5b083.png">

Does this meet your requirement?

**Comment by fmigneault** [comment]
@tonybaloney 
Thanks for this update. Looks great!
I’ll have to try it out, but it looks like it would resolve the issue.

**Comment by tonybaloney** [comment]
Shipped in 1.28.0 (update should show by tomorrow)
