### ISSUE TITLE
Possible false positive PW100 warning

### ISSUE THREAD

**Issue by liiight** [tonybaloney/pycharm-security#39]
I get the following warning:

![image](https://user-images.githubusercontent.com/4374581/73648449-4119e700-4686-11ea-8162-b285f9cf86bd.png)

Is this relevant even for `None` via the `is` comparator?

**Comment by tonybaloney** [comment]
has optimized and tweaked in https://github.com/tonybaloney/pycharm-security/pull/32
the 1.4.2 version just got approved in the marketplace, so if you update that warning should disappear.

**Comment by liiight** [comment]
Verified. Thank you for this plugin and I apologize for not trying to update first.
