### ISSUE TITLE
AST100 warning on asserts in Docstring

### ISSUE THREAD

**Issue by liiight** [tonybaloney/pycharm-security#40]
I got the following error:

![image](https://user-images.githubusercontent.com/4374581/73654516-9826b880-4694-11ea-9553-f740cdc97cbe.png)

Version: 1.4.2

**Comment by tonybaloney** [comment]
Wow, I didn't know it would inspect docstrings! 
This is an interesting use case...

**Comment by tonybaloney** [comment]
<img width="1338" alt="Screen Shot 2020-02-05 at 6 19 29 pm" src="https://user-images.githubusercontent.com/1532417/73819645-1a091400-4844-11ea-9838-b74e5c2c034d.png">

This is a configuration setting in PyCharm

**Comment by tonybaloney** [comment]
Available in 1.11.0
