### ISSUE TITLE
Shell error causes GitHub action to fail when no warnings are found

### ISSUE THREAD

**Issue by jjm** [tonybaloney/pycharm-security#70]
**Describe the bug**

When no JSON files get created in `out/` the following line in `action.sh`, causes the action to fail.

https://github.com/tonybaloney/pycharm-security/blob/e4ad38c32d41418c1e8f9001723a06cbecbf4f92/.github/actions/action.sh#L8

**To Reproduce**
Code or Steps to reproduce the behavior:
1. Setup a Python project to be checked with **pycharm-security**.
2. Fix any reported errors.
3. Have GitHub action run again.
4. Action fails.

**Expected behavior**

The GitHub Action is successful and a message is displayed.

**Screenshots**

The following is the output from the action when it fails. 

```
Run tonybaloney/pycharm-security@1.8.0
<deleted-doccker-command>
Scanning src/ with profile /sources/SecurityInspectionProfile.xml
cat: 'out/*.json': No such file or directory
Traceback (most recent call last):
  File "/code/parse.py", line 23, in <module>
    main()
  File "/code/parse.py", line 6, in main
    data = json.load(sys.stdin)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Found issues in code
##[error]Docker run failed with exit code 1
```

**Additional context**
 - **Plugin Version:** 1.8.0
 - **PyCharm Version (or IDE version):** n/a
 - **Python Version:** n/a

**Comment by jjm** [comment]
I think this is a quick fix, I'll look to raise a PR today.

**Comment by tonybaloney** [comment]
Eek! Well spotted jjm
