### ISSUE TITLE
Too much wiggly lines

### ISSUE THREAD

**Issue by jugmac00** [tonybaloney/pycharm-security#82]
**Describe the bug**
When there is a security issue, not only the associated line is "wiggled", but also the indented following line... but not only the code, but right from the line start.

**To Reproduce**
Code or Steps to reproduce the behavior:
Use a similar code to the screenshot.
P.S.: Maybe I spotted another bug... when the code (from screenshot) is within a method, it is spotted as a security issue. Is the code on module level, no issue gets reported.

**Expected behavior**
wiggly line only below code

**Screenshots**
![Screenshot from 2020-02-20 14-07-37](https://user-images.githubusercontent.com/9895620/74936640-ce7d6b00-53ea-11ea-8bf1-53dc9fb71f61.png)

**Additional context**
 - Plugin Version 1.10
 - PyCharm Version (or IDE version): IntelliJ 2019.3.3 Ultimate
 - Python Version 2.7

**Comment by tonybaloney** [comment]
It will highlight the range of the entire except statement (from the first character to the last), including whitespace. Agree that it looks ugly, but it's expected behaviour

**Comment by jugmac00** [comment]
There is no accounting for taste.
