### ISSUE TITLE
getQualifiedName don't detect the full name properly

### ISSUE THREAD

**Issue by ehooo** [tonybaloney/pycharm-security#86]
**Describe the bug**
QualifiedNameHelpers.getQualifiedName are not getting properly the quialified name.

**To Reproduce**
Code to reproduce:
```python
from django.utils import safestring

safestring.SafeText('<b>secure</b>')
```

**Expected behavior**
DJG102 rule must be triggered

**Screenshots**
Here you are an screenshot with the 
![image](https://user-images.githubusercontent.com/709565/75110374-c82b0100-562d-11ea-98f1-8b0b928834cd.png)

**Additional context**
 - Plugin Version: 1.11.0
 - PyCharm Version (or IDE version): 2019.3 Community
 - Python Version: 3.7

**Comment by tonybaloney** [comment]
Is this from a unit test or a `runIde` session?

Inside the unit tests, it doesn't load the standard library, or the Python environment so the qualified name resolver goes to the second branch in the function (which makes the tests a lot harder!).

Inside a `runIde` debug session, you must make sure that the python environment is configured in PyCharm/IntelliJ, INSIDE the debug IDE (look at the status bar at the bottom).

**Comment by ehooo** [comment]
I use `runIde` and also on my usual version is not maked as error, only in the class objects, the `mark_safe`function is working fine
