### ISSUE TITLE
TRY101 raises warning for specific exception

### ISSUE THREAD

**Issue by jugmac00** [tonybaloney/pycharm-security#88]
**Describe the bug**
I get a security warning although I expect the exception.

**To Reproduce**
I have a for loop and I want to do something to each item, but only if the item has a Catalog set, else skip them.

```
        for class_ in data.values():
            try:
                catalog = class_.Catalog
            except AttributeError:
                continue
```

**Expected behavior**
As I specify the exception, and expect it, I do not think this is a security issue.

**Additional context**
 - Plugin Version: 1.12
 - PyCharm Version (or IDE version) IntelliJ Ultimate 2019.3.3
 - Python Version 2.7 :-(

This bug report is similar to #80

**Comment by ehooo** [comment]
@jugmac00 this issue was fixed
