### ISSUE TITLE
PyCharm 2020.1 API changes

### ISSUE THREAD

**Issue by lada-gagina** [tonybaloney/pycharm-security#89]
There will be some breaking changes in PyCharm 2020.1 API:

- `com.jetbrains.python.psi.PyCallExpression.PyMarkedCallee` will be replaced by `com.jetbrains.python.psi.types.PyCallableType`
- `com.jetbrains.python.psi.PyCallExpression#multiResolveCallee(com.jetbrains.python.psi.resolve.PyResolveContext)` will return `List<PyCallableType>` instead of `List<PyMarkedCallee>`

**Comment by tonybaloney** [comment]
Thanks for the heads up, I need to work out how to test this on both 2019.3 and 2020.1 so I can publish a release that works across both APIs

**Comment by tonybaloney** [comment]
I over-eagerly merged it, but it doesn't look like this change is on `'201-EAP-SNAPSHOT'` yet, so I'll bring and test the changes once there's a snapshot build on maven

**Comment by tonybaloney** [comment]
Created feature branch https://github.com/tonybaloney/pycharm-security/tree/2020.1-EAP to merge-forward into for now
