### ISSUE TITLE
Detect insecure use of format

### ISSUE THREAD

**Issue by ehooo** [tonybaloney/pycharm-security#95]
Detect insecure use of format

If this is a check:
- What it scans for
calls to format
- Why
Add new rule
- References to documentation on why this is an issue
https://lucumr.pocoo.org/2016/12/29/careful-with-str-format/

If this is a general feature:
- Is it for PyCharm

**Comment by ehooo** [comment]
Hi @tonybaloney I will doit if you want.

As far I know to add new rule is required add:
- New class/file StrFormatInspection.kt on main/java/security/validators/
- The rule on Checks.kt
- A test on StrFormatInspectionTest
- A doc on doc/checks

Please let me know if i'm forget anything.
Could you tell me the Rule code?

Regards

**Comment by tonybaloney** [comment]
You also have to add a line in plugin.xml

This vulnerability is crazy! I didn’t know you could do that

**Comment by tonybaloney** [comment]
Does it apply to f-strings as well?

**Comment by ehooo** [comment]
As far I know about that vulnerability f-strings are not affected cause the attacker cannot manage the f-string so anything can be injected
